### ISSUE TITLE
2 Small feature requests

### ISSUE THREAD

**Issue by STaRDoGG** [MicrosoftEdge/edge-launcher#5]
Works great, can you add these 2 small things to it, to perfect it? :)

1). Add the Edge icon as it's icon. That way, programs that extract a program's icon from it's .exe, will use the actual Edge icon as well.

2). If launched without any URL as a param, just launch Edge itself. Currently it just flashes the cmd window, then closes.

**Comment by jckleinbourg** [comment]
Hello, I did a fork with the improvments you asked : https://github.com/jckleinbourg/MicrosoftEdgeLauncher/releases/tag/1.0.9.0

btw theres a strange behaviour when launching Edge itself, please tell me if it works correctly for you (see pull requests)

**Comment by STaRDoGG** [comment]
Thank you! Grabbing it now. Will report back if I get any strange behavior.

**Comment by jckleinbourg** [comment]
YW STaRDoGG
I don't know if you use the last version of Edge (25.10586.0.0), but this one seems to have a bug when trying to launch it with an empty page. If you start the launcher without argument, it should launch Edge the same way that you launch it when you execute the command "microsoft-edge:", but it doesn't show the default page and it is not possible to go to any url.

I reported this bug here:
http://answers.microsoft.com/en-us/windows/forum/apps_windows_10-msedge/starting-edge-from-command-line-causes-dysfunction/307d9332-95f9-4568-8452-4647fa106dd2?tm=1448118214274

and here:
https://social.technet.microsoft.com/Forums/en-US/5feaafea-5f1e-4fd5-a96b-c002e7633570/starting-edge-from-command-line-causes-dysfunction-on-latest-builds?forum=win10itprogeneral

I don't have any answer yet.
So if you use the last up-to-date Edge version, could you please tell me if it works for you?

**Comment by STaRDoGG** [comment]
Is there a way to manually grab the latest version of Edge, outside of Windows Update? According to my Win Update, I'm all caught up, but my Edge version only shows 20.10240.16384.0, which is working great with the launcher. No problem with launching it alone and not having a start page.

**Comment by STaRDoGG** [comment]
I'm having a problem using the launcher on locally saved .htm/.html files, where double-clicking it loads Edge, but the page itself doesn't load. Does the same happen for you as well?

**Comment by jckleinbourg** [comment]
MicrosoftEdgeLauncher.exe doesn't work on local html files. When trying to launch a local html page on Andy's first release 1.0.0.0, It starts a new instance of Edge at starting default page.
On my release 1.0.9.0, it launch Edge (if not already happen) but the screen is blank and there's no possibility to go to any other page (like when launching the tool with no option). I reported this bug on Edge developers forum but get no answer yet.

An alternative is to use the command `explorer` like `explorer http://www.google.com` or `explorer c:/mypage.html`. It works well in both case, but it needs of course to have Edge as your default browser, that might not be the case for you.

**Comment by STaRDoGG** [comment]
Interesting, on my version (your 1.0.9.0), if I start the launcher either empty, or by dbl clicking a .htm file, it loads up the start page (and any previously opened pages as well, if so, because I have that option selected), and I can use Edge as normal; open new tabs, etc., I'm not stuck not being able to go to any other page.

I've tried it by directly dbl-clicking the launcher, as well as my usual way of opening web pages; I have [Browser Chooser 2](https://browserchooser2.codeplex.com/) set as my default browser, then have Edge launcher added as one of the browsers to be able to select from.

Really kinda strange that Edge can't read local pages. Is this happening only with local pages via the launcher? Or does it happen as well if Edge itself is set as the default browser? (I haven't tested it myself :) )

**Comment by nickmccurdy** [comment]
> Really kinda strange that Edge can't read local pages.
This shouldn't be an issue since the stable release of Windows 10. I remember the problem back when I was on the preview, but I can use `file:///` URLs now.
